from selenium.webdriver.common.by import By
# credit_card_lcs[""] = (By.CSS_SELECTOR, "")
credit_card_lcs = dict()

credit_card_lcs["x_btn"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > span")
credit_card_lcs["card_num_fld"] = (By.CSS_SELECTOR, '#credit-card-input')
credit_card_lcs["id_num_fld"] = (By.CSS_SELECTOR, "#userId-input")
# Card validity
credit_card_lcs["month"] = (By.CSS_SELECTOR, "#expmonth")
credit_card_lcs["month1"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(2)")
credit_card_lcs["month2"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(3)")
credit_card_lcs["month3"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(4)")
credit_card_lcs["month4"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(5)")
credit_card_lcs["month5"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(6)")
credit_card_lcs["month6"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(7)")
credit_card_lcs["month7"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(8)")
credit_card_lcs["month8"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(9)")
credit_card_lcs["month9"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(10)")
credit_card_lcs["month10"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(11)")
credit_card_lcs["month11"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(12)")
credit_card_lcs["month12"] = (By.CSS_SELECTOR, "#expmonth > option:nth-child(13)")
credit_card_lcs["year"] = (By.CSS_SELECTOR, "#expyear")
credit_card_lcs["year23"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(2)")
credit_card_lcs["year24"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(3)")
credit_card_lcs["year25"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(4)")
credit_card_lcs["year26"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(5)")
credit_card_lcs["year27"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(6)")
credit_card_lcs["year28"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(7)")
credit_card_lcs["year29"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(8)")
credit_card_lcs["year30"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(9)")
credit_card_lcs["year31"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(10)")
credit_card_lcs["year32"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(11)")
credit_card_lcs["year33"] = (By.CSS_SELECTOR, "#expyear > option:nth-child(12)")
credit_card_lcs["cvv"] = (By.CSS_SELECTOR, "#cvv")
credit_card_lcs["submit"] = (By.CSS_SELECTOR, "#btnSubmit")