from selenium.webdriver.common.by import By
# = (By.CSS_SELECTOR, "")
sign_up_lcs = dict()
# Page 1
sign_up_lcs["x_btn"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > span > i")
sign_up_lcs["signUp_btn"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > div.login_loginregister > span:nth-child(2)")
sign_up_lcs["facebook"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > div.login_socialLogin > div.login_socialLoginButtons > span > button")
sign_up_lcs["google"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > div.login_socialLogin > div.login_socialLoginButtons > button")
sign_up_lcs["twitter"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > div.login_socialLogin > div.login_socialLoginButtons > div")
sign_up_lcs["phone_fld"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div:nth-child(1) > div:nth-child(1) > span > input[type=tel]")
sign_up_lcs["bnNum_fld"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div:nth-child(1) > div:nth-child(2) > span > input[type=number]")
sign_up_lcs["accept_policy"] = (By.XPATH, '//*[@id="root"]/div/div[4]/div/div/div/div/form/div[1]/div[3]/span/span')
sign_up_lcs["accept_sent_emails"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div:nth-child(1) > div:nth-child(4) > span > span > span > i")
sign_up_lcs["logIn_btn"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > input")
# Page 2
sign_up_lcs["1input_number_fld"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div.form_loginCode > div:nth-child(1) > span > input")
sign_up_lcs["2input_number_fld"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div.form_loginCode > div:nth-child(2) > span > input")
sign_up_lcs["3input_number_fld"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div.form_loginCode > div:nth-child(3) > span > input")
sign_up_lcs["4input_number_fld"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div.form_loginCode > div:nth-child(4) > span > input")
sign_up_lcs["5input_number_fld"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div.form_loginCode > div:nth-child(5) > span > input")
sign_up_lcs["verify_btn"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > input")
sign_up_lcs["resent_msg_btn"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > div.login_sms")

# asserts
sign_up_lcs["invalid_number"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div:nth-child(1) > div:nth-child(1) > div")
sign_up_lcs["empty_bn_fld"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div.form_message")
sign_up_lcs["no_accept_policy"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div.form_message")
sign_up_lcs["bnnum_div"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div:nth-child(1) > div:nth-child(2)")
sign_up_lcs["choose_cocktail"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > div > div.login_interestsContainer > div:nth-child(1)")
sign_up_lcs["choose_rest"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > div > div.login_interestsContainer > div:nth-child(2)")
sign_up_lcs["create_acc_btn"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > div > div:nth-child(3) > button")
sign_up_lcs["invalid_code_msg"] = (By.CSS_SELECTOR, "#root > div > div.modal_modalWrapper.false.modal_open > div > div > div > div > form > div.form_message")
sign_up_lcs[""] = (By.CSS_SELECTOR, "")
sign_up_lcs[""] = (By.CSS_SELECTOR, "")
